create table if not exists hits
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    app       varchar(255) not null,
    uri       varchar(255) not null,
    ip        varchar(15) not null,
    timestamp TIMESTAMP    not null
);